# Generated by Django 5.1.2 on 2025-01-22 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(help_text='выбирите автора книги', to='catalog.author', verbose_name='Автор книги'),
        ),
    ]
