# Generated by Django 5.1.2 on 2025-03-09 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_bookinstance_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookinstance',
            old_name='in_nom',
            new_name='inv_nom',
        ),
    ]
